/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DeFiToken__factory } from "./DeFiToken__factory";
export { StakingPool__factory } from "./StakingPool__factory";
